import type { EcdCentre } from "@/lib/centres/types";

const activity = (centre: string) => [
  {
    id: `${centre}-activity-1`,
    title: "Profile updated",
    description: "Contact details and child count reviewed by ECDLink.",
    createdAt: "2026-07-06",
    type: "profile" as const
  },
  {
    id: `${centre}-activity-2`,
    title: "Compliance reminder sent",
    description: "SARS Tax Pin and committee ID reminders queued.",
    createdAt: "2026-07-03",
    type: "compliance" as const
  },
  {
    id: `${centre}-activity-3`,
    title: "Monthly procurement cycle opened",
    description: "Centre can now submit July procurement basket.",
    createdAt: "2026-07-01",
    type: "procurement" as const
  }
];

const photos = (centre: string, tone: string) => [
  { id: `${centre}-photo-1`, title: "Classroom view", tone, uploadedAt: "2026-06-20" },
  { id: `${centre}-photo-2`, title: "Outdoor play area", tone, uploadedAt: "2026-06-20" }
];

export const seededCentres: EcdCentre[] = [
  {
    id: "little-stars-ecd",
    centreName: "Little Stars ECD Centre",
    registrationStatus: "Registered",
    npoNumber: "NPO-184-226",
    dbeRegistrationStatus: "DBE registered",
    physicalAddress: "42 Makhaza Road, Khayelitsha, Cape Town, 7784",
    area: "Khayelitsha",
    region: "Western Cape",
    contactPerson: "Nomsa Dlamini",
    phoneNumber: "+27 71 482 1140",
    emailAddress: "nomsa@littlestars.org.za",
    numberOfChildren: 64,
    numberOfStaff: 8,
    principalName: "Nomsa Dlamini",
    membershipStatus: "Active",
    procurementStatus: "Active",
    complianceStatus: "Attention",
    fundingReadinessStatus: "In Progress",
    centrePhotos: photos("little-stars-ecd", "bg-blue-100"),
    notes: [{ id: "note-1", author: "ECDLink Admin", body: "Strong candidate for nutrition support grant.", createdAt: "2026-07-05" }],
    activityTimeline: activity("little-stars-ecd"),
    createdDate: "2025-11-10",
    lastUpdatedDate: "2026-07-06"
  },
  {
    id: "bright-steps-centre",
    centreName: "Bright Steps Centre",
    registrationStatus: "Registered",
    npoNumber: "NPO-209-771",
    dbeRegistrationStatus: "Partial care approved",
    physicalAddress: "18 Vilakazi Extension, Soweto, Johannesburg, 1804",
    area: "Soweto",
    region: "Gauteng",
    contactPerson: "Thandi Mokoena",
    phoneNumber: "+27 82 334 0198",
    emailAddress: "admin@brightsteps.org.za",
    numberOfChildren: 78,
    numberOfStaff: 10,
    principalName: "Thandi Mokoena",
    membershipStatus: "Active",
    procurementStatus: "Active",
    complianceStatus: "Compliant",
    fundingReadinessStatus: "Ready",
    centrePhotos: photos("bright-steps-centre", "bg-green-100"),
    notes: [],
    activityTimeline: activity("bright-steps-centre"),
    createdDate: "2025-12-02",
    lastUpdatedDate: "2026-07-04"
  },
  {
    id: "ubuntu-kids",
    centreName: "Ubuntu Kids",
    registrationStatus: "In Progress",
    npoNumber: "Pending",
    dbeRegistrationStatus: "Partial care in progress",
    physicalAddress: "7 Mangosuthu Highway, Umlazi, Durban, 4066",
    area: "Umlazi",
    region: "KwaZulu-Natal",
    contactPerson: "Zanele Gumede",
    phoneNumber: "+27 73 901 4431",
    emailAddress: "hello@ubuntukids.org.za",
    numberOfChildren: 52,
    numberOfStaff: 6,
    principalName: "Zanele Gumede",
    membershipStatus: "Pending",
    procurementStatus: "Pending",
    complianceStatus: "Action Required",
    fundingReadinessStatus: "Needs Attention",
    centrePhotos: photos("ubuntu-kids", "bg-amber-100"),
    notes: [{ id: "note-2", author: "Compliance Desk", body: "Needs NPO confirmation and committee IDs.", createdAt: "2026-07-02" }],
    activityTimeline: activity("ubuntu-kids"),
    createdDate: "2026-01-14",
    lastUpdatedDate: "2026-07-02"
  },
  {
    id: "future-leaders-ecd",
    centreName: "Future Leaders ECD",
    registrationStatus: "Registered",
    npoNumber: "NPO-198-554",
    dbeRegistrationStatus: "DBE registered",
    physicalAddress: "91 Tsamaya Avenue, Mamelodi, Pretoria, 0122",
    area: "Mamelodi",
    region: "Gauteng",
    contactPerson: "Lerato Nkosi",
    phoneNumber: "+27 76 229 7740",
    emailAddress: "lerato@futureleaders.org.za",
    numberOfChildren: 96,
    numberOfStaff: 12,
    principalName: "Lerato Nkosi",
    membershipStatus: "Active",
    procurementStatus: "Active",
    complianceStatus: "Compliant",
    fundingReadinessStatus: "Ready",
    centrePhotos: photos("future-leaders-ecd", "bg-slate-100"),
    notes: [],
    activityTimeline: activity("future-leaders-ecd"),
    createdDate: "2025-10-22",
    lastUpdatedDate: "2026-07-01"
  },
  ...[
    ["ikamva-labantwana", "Ikamva Labantwana", "Philippi", "Western Cape", 58],
    ["happy-hearts-ecd", "Happy Hearts ECD", "Mitchells Plain", "Western Cape", 44],
    ["siyakhula-centre", "Siyakhula Centre", "Alexandra", "Gauteng", 61],
    ["tiny-seeds", "Tiny Seeds", "Tembisa", "Gauteng", 49],
    ["masakhane-kids", "Masakhane Kids", "Khayelitsha", "Western Cape", 72],
    ["little-sunshine", "Little Sunshine", "Umlazi", "KwaZulu-Natal", 37],
    ["hope-garden-ecd", "Hope Garden ECD", "Mamelodi", "Gauteng", 83],
    ["sisonke-early-learning", "Sisonke Early Learning", "Philippi", "Western Cape", 55],
    ["khula-nathi", "Khula Nathi", "Soweto", "Gauteng", 69],
    ["bright-futures-kids", "Bright Futures Kids", "Tembisa", "Gauteng", 47],
    ["morning-star-ecd", "Morning Star ECD", "Mitchells Plain", "Western Cape", 41],
    ["new-dawn-centre", "New Dawn Centre", "Alexandra", "Gauteng", 74]
  ].map(([id, name, area, region, children], index) => ({
    id: String(id),
    centreName: String(name),
    registrationStatus: index % 5 === 0 ? "In Progress" as const : "Registered" as const,
    npoNumber: index % 5 === 0 ? "Pending" : `NPO-${180 + index}-${430 + index}`,
    dbeRegistrationStatus: index % 3 === 0 ? "Partial care approved" : "DBE registered",
    physicalAddress: `${12 + index} Community Road, ${area}`,
    area: String(area),
    region: String(region),
    contactPerson: ["Ayanda", "Mpho", "Noluthando", "Sipho"][index % 4] + " Manager",
    phoneNumber: `+27 7${index} 555 ${1000 + index}`,
    emailAddress: `centre${index + 5}@ecdlink.org.za`,
    numberOfChildren: Number(children),
    numberOfStaff: 5 + (index % 7),
    principalName: ["Ayanda", "Mpho", "Noluthando", "Sipho"][index % 4] + " Manager",
    membershipStatus: index % 4 === 0 ? "Pending" as const : "Active" as const,
    procurementStatus: index % 3 === 0 ? "Pending" as const : "Active" as const,
    complianceStatus: index % 4 === 0 ? "Action Required" as const : index % 3 === 0 ? "Attention" as const : "Compliant" as const,
    fundingReadinessStatus: index % 4 === 0 ? "Needs Attention" as const : index % 3 === 0 ? "In Progress" as const : "Ready" as const,
    centrePhotos: photos(String(id), index % 2 === 0 ? "bg-blue-100" : "bg-green-100"),
    notes: [],
    activityTimeline: activity(String(id)),
    createdDate: `2026-0${(index % 6) + 1}-12`,
    lastUpdatedDate: "2026-07-01"
  }))
];
