"use client";

import { useRouter } from "next/navigation";
import { MessageSquarePlus } from "lucide-react";
import { WorkflowActionDialog, type WorkflowActionResult } from "@/components/workflows/workflow-action-dialog";
import { StatusBadge } from "@/components/design-system";
import type { FundingCommunicationRecord } from "@/lib/funding/types";

export function FundingCommunicationHistory({ applicationId, communications }: { applicationId: string | null; communications: FundingCommunicationRecord[] }) {
  const router = useRouter();
  if (!applicationId) return <p className="rounded-lg border border-dashed border-brand-line p-8 text-center text-sm text-slate-500">Create an application before recording communication.</p>;
  return <div className="space-y-4"><WorkflowActionDialog<{ title: string; body: string }> title="Record applicant communication" description="Record a formal funding update and send an in-app notification." trigger={{ label: "New communication", variant: "primary", icon: <MessageSquarePlus className="h-4 w-4" /> }} confirmationButton={{ label: "Record and notify", loadingLabel: "Recording…" }} fields={[{ name: "title", type: "text", label: "Title", required: true, maxLength: 200 }, { name: "body", type: "textarea", label: "Message", required: true, rows: 6, maxLength: 10000 }]} initialValues={{ title: "", body: "" }} action={async (values): Promise<WorkflowActionResult> => { const response = await fetch(`/api/funding/applications/${applicationId}/communications`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "MANUAL", title: values.title.trim(), body: values.body.trim() }) }); const result = await response.json(); return response.ok && result.ok ? { ok: true } : { ok: false, error: result.error ?? "Communication could not be recorded." }; }} successToast={{ title: "Communication recorded", description: "An in-app notification was sent where an active recipient was available." }} errorToast={{ title: "Communication failed", fallbackDescription: "Communication could not be recorded." }} onSuccess={() => router.refresh()} />{communications.length ? communications.map((item) => <article key={item.id} className="rounded-lg border border-brand-line p-4 dark:border-slate-800"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{item.title}</p><p className="text-xs text-slate-500">{item.author} → {item.recipient}</p></div><div className="text-right"><StatusBadge status={item.type} /><p className="mt-1 text-xs text-slate-500">{new Date(item.createdAt).toLocaleString()}</p></div></div><p className="mt-3 whitespace-pre-wrap text-sm text-slate-700 dark:text-slate-200">{item.body}</p></article>) : <p className="rounded-lg border border-dashed border-brand-line p-8 text-center text-sm text-slate-500">No applicant communication has been recorded.</p>}</div>;
}
